// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_HYPERHDRREQUEST_HYPERHDRNET_H_
#define FLATBUFFERS_GENERATED_HYPERHDRREQUEST_HYPERHDRNET_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace hyperhdrnet {

struct Register;
struct RegisterBuilder;
struct RegisterT;

struct RawImage;
struct RawImageBuilder;
struct RawImageT;

struct NV12Image;
struct NV12ImageBuilder;
struct NV12ImageT;

struct Image;
struct ImageBuilder;
struct ImageT;

struct Clear;
struct ClearBuilder;
struct ClearT;

struct Color;
struct ColorBuilder;
struct ColorT;

struct Request;
struct RequestBuilder;
struct RequestT;

enum ImageType : uint8_t {
  ImageType_NONE = 0,
  ImageType_RawImage = 1,
  ImageType_NV12Image = 2,
  ImageType_MIN = ImageType_NONE,
  ImageType_MAX = ImageType_NV12Image
};

inline const ImageType (&EnumValuesImageType())[3] {
  static const ImageType values[] = {
    ImageType_NONE,
    ImageType_RawImage,
    ImageType_NV12Image
  };
  return values;
}

inline const char * const *EnumNamesImageType() {
  static const char * const names[4] = {
    "NONE",
    "RawImage",
    "NV12Image",
    nullptr
  };
  return names;
}

inline const char *EnumNameImageType(ImageType e) {
  if (::flatbuffers::IsOutRange(e, ImageType_NONE, ImageType_NV12Image)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesImageType()[index];
}

template<typename T> struct ImageTypeTraits {
  static const ImageType enum_value = ImageType_NONE;
};

template<> struct ImageTypeTraits<hyperhdrnet::RawImage> {
  static const ImageType enum_value = ImageType_RawImage;
};

template<> struct ImageTypeTraits<hyperhdrnet::NV12Image> {
  static const ImageType enum_value = ImageType_NV12Image;
};

template<typename T> struct ImageTypeUnionTraits {
  static const ImageType enum_value = ImageType_NONE;
};

template<> struct ImageTypeUnionTraits<hyperhdrnet::RawImageT> {
  static const ImageType enum_value = ImageType_RawImage;
};

template<> struct ImageTypeUnionTraits<hyperhdrnet::NV12ImageT> {
  static const ImageType enum_value = ImageType_NV12Image;
};

struct ImageTypeUnion {
  ImageType type;
  void *value;

  ImageTypeUnion() : type(ImageType_NONE), value(nullptr) {}
  ImageTypeUnion(ImageTypeUnion&& u) FLATBUFFERS_NOEXCEPT :
    type(ImageType_NONE), value(nullptr)
    { std::swap(type, u.type); std::swap(value, u.value); }
  ImageTypeUnion(const ImageTypeUnion &);
  ImageTypeUnion &operator=(const ImageTypeUnion &u)
    { ImageTypeUnion t(u); std::swap(type, t.type); std::swap(value, t.value); return *this; }
  ImageTypeUnion &operator=(ImageTypeUnion &&u) FLATBUFFERS_NOEXCEPT
    { std::swap(type, u.type); std::swap(value, u.value); return *this; }
  ~ImageTypeUnion() { Reset(); }

  void Reset();

  template <typename T>
  void Set(T&& val) {
    typedef typename std::remove_reference<T>::type RT;
    Reset();
    type = ImageTypeUnionTraits<RT>::enum_value;
    if (type != ImageType_NONE) {
      value = new RT(std::forward<T>(val));
    }
  }

  static void *UnPack(const void *obj, ImageType type, const ::flatbuffers::resolver_function_t *resolver);
  ::flatbuffers::Offset<void> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr) const;

  hyperhdrnet::RawImageT *AsRawImage() {
    return type == ImageType_RawImage ?
      reinterpret_cast<hyperhdrnet::RawImageT *>(value) : nullptr;
  }
  const hyperhdrnet::RawImageT *AsRawImage() const {
    return type == ImageType_RawImage ?
      reinterpret_cast<const hyperhdrnet::RawImageT *>(value) : nullptr;
  }
  hyperhdrnet::NV12ImageT *AsNV12Image() {
    return type == ImageType_NV12Image ?
      reinterpret_cast<hyperhdrnet::NV12ImageT *>(value) : nullptr;
  }
  const hyperhdrnet::NV12ImageT *AsNV12Image() const {
    return type == ImageType_NV12Image ?
      reinterpret_cast<const hyperhdrnet::NV12ImageT *>(value) : nullptr;
  }
};

template <bool B = false>
bool VerifyImageType(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, ImageType type);
template <bool B = false>
bool VerifyImageTypeVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

enum Command : uint8_t {
  Command_NONE = 0,
  Command_Color = 1,
  Command_Image = 2,
  Command_Clear = 3,
  Command_Register = 4,
  Command_MIN = Command_NONE,
  Command_MAX = Command_Register
};

inline const Command (&EnumValuesCommand())[5] {
  static const Command values[] = {
    Command_NONE,
    Command_Color,
    Command_Image,
    Command_Clear,
    Command_Register
  };
  return values;
}

inline const char * const *EnumNamesCommand() {
  static const char * const names[6] = {
    "NONE",
    "Color",
    "Image",
    "Clear",
    "Register",
    nullptr
  };
  return names;
}

inline const char *EnumNameCommand(Command e) {
  if (::flatbuffers::IsOutRange(e, Command_NONE, Command_Register)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCommand()[index];
}

template<typename T> struct CommandTraits {
  static const Command enum_value = Command_NONE;
};

template<> struct CommandTraits<hyperhdrnet::Color> {
  static const Command enum_value = Command_Color;
};

template<> struct CommandTraits<hyperhdrnet::Image> {
  static const Command enum_value = Command_Image;
};

template<> struct CommandTraits<hyperhdrnet::Clear> {
  static const Command enum_value = Command_Clear;
};

template<> struct CommandTraits<hyperhdrnet::Register> {
  static const Command enum_value = Command_Register;
};

template<typename T> struct CommandUnionTraits {
  static const Command enum_value = Command_NONE;
};

template<> struct CommandUnionTraits<hyperhdrnet::ColorT> {
  static const Command enum_value = Command_Color;
};

template<> struct CommandUnionTraits<hyperhdrnet::ImageT> {
  static const Command enum_value = Command_Image;
};

template<> struct CommandUnionTraits<hyperhdrnet::ClearT> {
  static const Command enum_value = Command_Clear;
};

template<> struct CommandUnionTraits<hyperhdrnet::RegisterT> {
  static const Command enum_value = Command_Register;
};

struct CommandUnion {
  Command type;
  void *value;

  CommandUnion() : type(Command_NONE), value(nullptr) {}
  CommandUnion(CommandUnion&& u) FLATBUFFERS_NOEXCEPT :
    type(Command_NONE), value(nullptr)
    { std::swap(type, u.type); std::swap(value, u.value); }
  CommandUnion(const CommandUnion &);
  CommandUnion &operator=(const CommandUnion &u)
    { CommandUnion t(u); std::swap(type, t.type); std::swap(value, t.value); return *this; }
  CommandUnion &operator=(CommandUnion &&u) FLATBUFFERS_NOEXCEPT
    { std::swap(type, u.type); std::swap(value, u.value); return *this; }
  ~CommandUnion() { Reset(); }

  void Reset();

  template <typename T>
  void Set(T&& val) {
    typedef typename std::remove_reference<T>::type RT;
    Reset();
    type = CommandUnionTraits<RT>::enum_value;
    if (type != Command_NONE) {
      value = new RT(std::forward<T>(val));
    }
  }

  static void *UnPack(const void *obj, Command type, const ::flatbuffers::resolver_function_t *resolver);
  ::flatbuffers::Offset<void> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr) const;

  hyperhdrnet::ColorT *AsColor() {
    return type == Command_Color ?
      reinterpret_cast<hyperhdrnet::ColorT *>(value) : nullptr;
  }
  const hyperhdrnet::ColorT *AsColor() const {
    return type == Command_Color ?
      reinterpret_cast<const hyperhdrnet::ColorT *>(value) : nullptr;
  }
  hyperhdrnet::ImageT *AsImage() {
    return type == Command_Image ?
      reinterpret_cast<hyperhdrnet::ImageT *>(value) : nullptr;
  }
  const hyperhdrnet::ImageT *AsImage() const {
    return type == Command_Image ?
      reinterpret_cast<const hyperhdrnet::ImageT *>(value) : nullptr;
  }
  hyperhdrnet::ClearT *AsClear() {
    return type == Command_Clear ?
      reinterpret_cast<hyperhdrnet::ClearT *>(value) : nullptr;
  }
  const hyperhdrnet::ClearT *AsClear() const {
    return type == Command_Clear ?
      reinterpret_cast<const hyperhdrnet::ClearT *>(value) : nullptr;
  }
  hyperhdrnet::RegisterT *AsRegister() {
    return type == Command_Register ?
      reinterpret_cast<hyperhdrnet::RegisterT *>(value) : nullptr;
  }
  const hyperhdrnet::RegisterT *AsRegister() const {
    return type == Command_Register ?
      reinterpret_cast<const hyperhdrnet::RegisterT *>(value) : nullptr;
  }
};

template <bool B = false>
bool VerifyCommand(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, Command type);
template <bool B = false>
bool VerifyCommandVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct RegisterT : public ::flatbuffers::NativeTable {
  typedef Register TableType;
  std::string origin{};
  int32_t priority = 0;
};

struct Register FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RegisterT NativeTableType;
  typedef RegisterBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ORIGIN = 4,
    VT_PRIORITY = 6
  };
  const ::flatbuffers::String *origin() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ORIGIN);
  }
  ::flatbuffers::String *mutable_origin() {
    return GetPointer<::flatbuffers::String *>(VT_ORIGIN);
  }
  int32_t priority() const {
    return GetField<int32_t>(VT_PRIORITY, 0);
  }
  bool mutate_priority(int32_t _priority = 0) {
    return SetField<int32_t>(VT_PRIORITY, _priority, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_ORIGIN) &&
           verifier.VerifyString(origin()) &&
           VerifyField<int32_t>(verifier, VT_PRIORITY, 4) &&
           verifier.EndTable();
  }
  RegisterT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(RegisterT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Register> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RegisterT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct RegisterBuilder {
  typedef Register Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_origin(::flatbuffers::Offset<::flatbuffers::String> origin) {
    fbb_.AddOffset(Register::VT_ORIGIN, origin);
  }
  void add_priority(int32_t priority) {
    fbb_.AddElement<int32_t>(Register::VT_PRIORITY, priority, 0);
  }
  explicit RegisterBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Register> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Register>(end);
    fbb_.Required(o, Register::VT_ORIGIN);
    return o;
  }
};

inline ::flatbuffers::Offset<Register> CreateRegister(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> origin = 0,
    int32_t priority = 0) {
  RegisterBuilder builder_(_fbb);
  builder_.add_priority(priority);
  builder_.add_origin(origin);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Register> CreateRegisterDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *origin = nullptr,
    int32_t priority = 0) {
  auto origin__ = origin ? _fbb.CreateString(origin) : 0;
  return hyperhdrnet::CreateRegister(
      _fbb,
      origin__,
      priority);
}

::flatbuffers::Offset<Register> CreateRegister(::flatbuffers::FlatBufferBuilder &_fbb, const RegisterT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct RawImageT : public ::flatbuffers::NativeTable {
  typedef RawImage TableType;
  std::vector<uint8_t> data{};
  int32_t width = -1;
  int32_t height = -1;
};

struct RawImage FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RawImageT NativeTableType;
  typedef RawImageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATA = 4,
    VT_WIDTH = 6,
    VT_HEIGHT = 8
  };
  const ::flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  ::flatbuffers::Vector<uint8_t> *mutable_data() {
    return GetPointer<::flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  int32_t width() const {
    return GetField<int32_t>(VT_WIDTH, -1);
  }
  bool mutate_width(int32_t _width = -1) {
    return SetField<int32_t>(VT_WIDTH, _width, -1);
  }
  int32_t height() const {
    return GetField<int32_t>(VT_HEIGHT, -1);
  }
  bool mutate_height(int32_t _height = -1) {
    return SetField<int32_t>(VT_HEIGHT, _height, -1);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           VerifyField<int32_t>(verifier, VT_WIDTH, 4) &&
           VerifyField<int32_t>(verifier, VT_HEIGHT, 4) &&
           verifier.EndTable();
  }
  RawImageT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(RawImageT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<RawImage> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RawImageT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct RawImageBuilder {
  typedef RawImage Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(RawImage::VT_DATA, data);
  }
  void add_width(int32_t width) {
    fbb_.AddElement<int32_t>(RawImage::VT_WIDTH, width, -1);
  }
  void add_height(int32_t height) {
    fbb_.AddElement<int32_t>(RawImage::VT_HEIGHT, height, -1);
  }
  explicit RawImageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RawImage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RawImage>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RawImage> CreateRawImage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data = 0,
    int32_t width = -1,
    int32_t height = -1) {
  RawImageBuilder builder_(_fbb);
  builder_.add_height(height);
  builder_.add_width(width);
  builder_.add_data(data);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<RawImage> CreateRawImageDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *data = nullptr,
    int32_t width = -1,
    int32_t height = -1) {
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  return hyperhdrnet::CreateRawImage(
      _fbb,
      data__,
      width,
      height);
}

::flatbuffers::Offset<RawImage> CreateRawImage(::flatbuffers::FlatBufferBuilder &_fbb, const RawImageT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct NV12ImageT : public ::flatbuffers::NativeTable {
  typedef NV12Image TableType;
  std::vector<uint8_t> data_y{};
  std::vector<uint8_t> data_uv{};
  int32_t width = 0;
  int32_t height = 0;
  int32_t stride_y = 0;
  int32_t stride_uv = 0;
};

struct NV12Image FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NV12ImageT NativeTableType;
  typedef NV12ImageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATA_Y = 4,
    VT_DATA_UV = 6,
    VT_WIDTH = 8,
    VT_HEIGHT = 10,
    VT_STRIDE_Y = 12,
    VT_STRIDE_UV = 14
  };
  const ::flatbuffers::Vector<uint8_t> *data_y() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA_Y);
  }
  ::flatbuffers::Vector<uint8_t> *mutable_data_y() {
    return GetPointer<::flatbuffers::Vector<uint8_t> *>(VT_DATA_Y);
  }
  const ::flatbuffers::Vector<uint8_t> *data_uv() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA_UV);
  }
  ::flatbuffers::Vector<uint8_t> *mutable_data_uv() {
    return GetPointer<::flatbuffers::Vector<uint8_t> *>(VT_DATA_UV);
  }
  int32_t width() const {
    return GetField<int32_t>(VT_WIDTH, 0);
  }
  bool mutate_width(int32_t _width = 0) {
    return SetField<int32_t>(VT_WIDTH, _width, 0);
  }
  int32_t height() const {
    return GetField<int32_t>(VT_HEIGHT, 0);
  }
  bool mutate_height(int32_t _height = 0) {
    return SetField<int32_t>(VT_HEIGHT, _height, 0);
  }
  int32_t stride_y() const {
    return GetField<int32_t>(VT_STRIDE_Y, 0);
  }
  bool mutate_stride_y(int32_t _stride_y = 0) {
    return SetField<int32_t>(VT_STRIDE_Y, _stride_y, 0);
  }
  int32_t stride_uv() const {
    return GetField<int32_t>(VT_STRIDE_UV, 0);
  }
  bool mutate_stride_uv(int32_t _stride_uv = 0) {
    return SetField<int32_t>(VT_STRIDE_UV, _stride_uv, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DATA_Y) &&
           verifier.VerifyVector(data_y()) &&
           VerifyOffset(verifier, VT_DATA_UV) &&
           verifier.VerifyVector(data_uv()) &&
           VerifyField<int32_t>(verifier, VT_WIDTH, 4) &&
           VerifyField<int32_t>(verifier, VT_HEIGHT, 4) &&
           VerifyField<int32_t>(verifier, VT_STRIDE_Y, 4) &&
           VerifyField<int32_t>(verifier, VT_STRIDE_UV, 4) &&
           verifier.EndTable();
  }
  NV12ImageT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(NV12ImageT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<NV12Image> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const NV12ImageT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct NV12ImageBuilder {
  typedef NV12Image Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_data_y(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data_y) {
    fbb_.AddOffset(NV12Image::VT_DATA_Y, data_y);
  }
  void add_data_uv(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data_uv) {
    fbb_.AddOffset(NV12Image::VT_DATA_UV, data_uv);
  }
  void add_width(int32_t width) {
    fbb_.AddElement<int32_t>(NV12Image::VT_WIDTH, width, 0);
  }
  void add_height(int32_t height) {
    fbb_.AddElement<int32_t>(NV12Image::VT_HEIGHT, height, 0);
  }
  void add_stride_y(int32_t stride_y) {
    fbb_.AddElement<int32_t>(NV12Image::VT_STRIDE_Y, stride_y, 0);
  }
  void add_stride_uv(int32_t stride_uv) {
    fbb_.AddElement<int32_t>(NV12Image::VT_STRIDE_UV, stride_uv, 0);
  }
  explicit NV12ImageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<NV12Image> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<NV12Image>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<NV12Image> CreateNV12Image(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data_y = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data_uv = 0,
    int32_t width = 0,
    int32_t height = 0,
    int32_t stride_y = 0,
    int32_t stride_uv = 0) {
  NV12ImageBuilder builder_(_fbb);
  builder_.add_stride_uv(stride_uv);
  builder_.add_stride_y(stride_y);
  builder_.add_height(height);
  builder_.add_width(width);
  builder_.add_data_uv(data_uv);
  builder_.add_data_y(data_y);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<NV12Image> CreateNV12ImageDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *data_y = nullptr,
    const std::vector<uint8_t> *data_uv = nullptr,
    int32_t width = 0,
    int32_t height = 0,
    int32_t stride_y = 0,
    int32_t stride_uv = 0) {
  auto data_y__ = data_y ? _fbb.CreateVector<uint8_t>(*data_y) : 0;
  auto data_uv__ = data_uv ? _fbb.CreateVector<uint8_t>(*data_uv) : 0;
  return hyperhdrnet::CreateNV12Image(
      _fbb,
      data_y__,
      data_uv__,
      width,
      height,
      stride_y,
      stride_uv);
}

::flatbuffers::Offset<NV12Image> CreateNV12Image(::flatbuffers::FlatBufferBuilder &_fbb, const NV12ImageT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ImageT : public ::flatbuffers::NativeTable {
  typedef Image TableType;
  hyperhdrnet::ImageTypeUnion data{};
  int32_t duration = -1;
};

struct Image FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ImageT NativeTableType;
  typedef ImageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATA_TYPE = 4,
    VT_DATA = 6,
    VT_DURATION = 8
  };
  hyperhdrnet::ImageType data_type() const {
    return static_cast<hyperhdrnet::ImageType>(GetField<uint8_t>(VT_DATA_TYPE, 0));
  }
  const void *data() const {
    return GetPointer<const void *>(VT_DATA);
  }
  template<typename T> const T *data_as() const;
  const hyperhdrnet::RawImage *data_as_RawImage() const {
    return data_type() == hyperhdrnet::ImageType_RawImage ? static_cast<const hyperhdrnet::RawImage *>(data()) : nullptr;
  }
  const hyperhdrnet::NV12Image *data_as_NV12Image() const {
    return data_type() == hyperhdrnet::ImageType_NV12Image ? static_cast<const hyperhdrnet::NV12Image *>(data()) : nullptr;
  }
  template<typename T> T *mutable_data_as();
  hyperhdrnet::RawImage *mutable_data_as_RawImage() {
    return data_type() == hyperhdrnet::ImageType_RawImage ? static_cast<hyperhdrnet::RawImage *>(mutable_data()) : nullptr;
  }
  hyperhdrnet::NV12Image *mutable_data_as_NV12Image() {
    return data_type() == hyperhdrnet::ImageType_NV12Image ? static_cast<hyperhdrnet::NV12Image *>(mutable_data()) : nullptr;
  }
  void *mutable_data() {
    return GetPointer<void *>(VT_DATA);
  }
  int32_t duration() const {
    return GetField<int32_t>(VT_DURATION, -1);
  }
  bool mutate_duration(int32_t _duration = -1) {
    return SetField<int32_t>(VT_DURATION, _duration, -1);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_DATA_TYPE, 1) &&
           VerifyOffsetRequired(verifier, VT_DATA) &&
           VerifyImageType(verifier, data(), data_type()) &&
           VerifyField<int32_t>(verifier, VT_DURATION, 4) &&
           verifier.EndTable();
  }
  ImageT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ImageT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Image> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ImageT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

template<> inline const hyperhdrnet::RawImage *Image::data_as<hyperhdrnet::RawImage>() const {
  return data_as_RawImage();
}

template<> inline hyperhdrnet::RawImage *Image::mutable_data_as<hyperhdrnet::RawImage>() {
  return mutable_data_as_RawImage();
}

template<> inline const hyperhdrnet::NV12Image *Image::data_as<hyperhdrnet::NV12Image>() const {
  return data_as_NV12Image();
}

template<> inline hyperhdrnet::NV12Image *Image::mutable_data_as<hyperhdrnet::NV12Image>() {
  return mutable_data_as_NV12Image();
}

struct ImageBuilder {
  typedef Image Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_data_type(hyperhdrnet::ImageType data_type) {
    fbb_.AddElement<uint8_t>(Image::VT_DATA_TYPE, static_cast<uint8_t>(data_type), 0);
  }
  void add_data(::flatbuffers::Offset<void> data) {
    fbb_.AddOffset(Image::VT_DATA, data);
  }
  void add_duration(int32_t duration) {
    fbb_.AddElement<int32_t>(Image::VT_DURATION, duration, -1);
  }
  explicit ImageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Image> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Image>(end);
    fbb_.Required(o, Image::VT_DATA);
    return o;
  }
};

inline ::flatbuffers::Offset<Image> CreateImage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    hyperhdrnet::ImageType data_type = hyperhdrnet::ImageType_NONE,
    ::flatbuffers::Offset<void> data = 0,
    int32_t duration = -1) {
  ImageBuilder builder_(_fbb);
  builder_.add_duration(duration);
  builder_.add_data(data);
  builder_.add_data_type(data_type);
  return builder_.Finish();
}

::flatbuffers::Offset<Image> CreateImage(::flatbuffers::FlatBufferBuilder &_fbb, const ImageT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ClearT : public ::flatbuffers::NativeTable {
  typedef Clear TableType;
  int32_t priority = 0;
};

struct Clear FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClearT NativeTableType;
  typedef ClearBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PRIORITY = 4
  };
  int32_t priority() const {
    return GetField<int32_t>(VT_PRIORITY, 0);
  }
  bool mutate_priority(int32_t _priority = 0) {
    return SetField<int32_t>(VT_PRIORITY, _priority, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_PRIORITY, 4) &&
           verifier.EndTable();
  }
  ClearT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ClearT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Clear> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClearT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ClearBuilder {
  typedef Clear Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_priority(int32_t priority) {
    fbb_.AddElement<int32_t>(Clear::VT_PRIORITY, priority, 0);
  }
  explicit ClearBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Clear> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Clear>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Clear> CreateClear(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t priority = 0) {
  ClearBuilder builder_(_fbb);
  builder_.add_priority(priority);
  return builder_.Finish();
}

::flatbuffers::Offset<Clear> CreateClear(::flatbuffers::FlatBufferBuilder &_fbb, const ClearT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ColorT : public ::flatbuffers::NativeTable {
  typedef Color TableType;
  int32_t data = -1;
  int32_t duration = -1;
};

struct Color FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ColorT NativeTableType;
  typedef ColorBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATA = 4,
    VT_DURATION = 6
  };
  int32_t data() const {
    return GetField<int32_t>(VT_DATA, -1);
  }
  bool mutate_data(int32_t _data = -1) {
    return SetField<int32_t>(VT_DATA, _data, -1);
  }
  int32_t duration() const {
    return GetField<int32_t>(VT_DURATION, -1);
  }
  bool mutate_duration(int32_t _duration = -1) {
    return SetField<int32_t>(VT_DURATION, _duration, -1);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_DATA, 4) &&
           VerifyField<int32_t>(verifier, VT_DURATION, 4) &&
           verifier.EndTable();
  }
  ColorT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ColorT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Color> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ColorT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ColorBuilder {
  typedef Color Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_data(int32_t data) {
    fbb_.AddElement<int32_t>(Color::VT_DATA, data, -1);
  }
  void add_duration(int32_t duration) {
    fbb_.AddElement<int32_t>(Color::VT_DURATION, duration, -1);
  }
  explicit ColorBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Color> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Color>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Color> CreateColor(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t data = -1,
    int32_t duration = -1) {
  ColorBuilder builder_(_fbb);
  builder_.add_duration(duration);
  builder_.add_data(data);
  return builder_.Finish();
}

::flatbuffers::Offset<Color> CreateColor(::flatbuffers::FlatBufferBuilder &_fbb, const ColorT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct RequestT : public ::flatbuffers::NativeTable {
  typedef Request TableType;
  hyperhdrnet::CommandUnion command{};
};

struct Request FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RequestT NativeTableType;
  typedef RequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_COMMAND_TYPE = 4,
    VT_COMMAND = 6
  };
  hyperhdrnet::Command command_type() const {
    return static_cast<hyperhdrnet::Command>(GetField<uint8_t>(VT_COMMAND_TYPE, 0));
  }
  const void *command() const {
    return GetPointer<const void *>(VT_COMMAND);
  }
  template<typename T> const T *command_as() const;
  const hyperhdrnet::Color *command_as_Color() const {
    return command_type() == hyperhdrnet::Command_Color ? static_cast<const hyperhdrnet::Color *>(command()) : nullptr;
  }
  const hyperhdrnet::Image *command_as_Image() const {
    return command_type() == hyperhdrnet::Command_Image ? static_cast<const hyperhdrnet::Image *>(command()) : nullptr;
  }
  const hyperhdrnet::Clear *command_as_Clear() const {
    return command_type() == hyperhdrnet::Command_Clear ? static_cast<const hyperhdrnet::Clear *>(command()) : nullptr;
  }
  const hyperhdrnet::Register *command_as_Register() const {
    return command_type() == hyperhdrnet::Command_Register ? static_cast<const hyperhdrnet::Register *>(command()) : nullptr;
  }
  template<typename T> T *mutable_command_as();
  hyperhdrnet::Color *mutable_command_as_Color() {
    return command_type() == hyperhdrnet::Command_Color ? static_cast<hyperhdrnet::Color *>(mutable_command()) : nullptr;
  }
  hyperhdrnet::Image *mutable_command_as_Image() {
    return command_type() == hyperhdrnet::Command_Image ? static_cast<hyperhdrnet::Image *>(mutable_command()) : nullptr;
  }
  hyperhdrnet::Clear *mutable_command_as_Clear() {
    return command_type() == hyperhdrnet::Command_Clear ? static_cast<hyperhdrnet::Clear *>(mutable_command()) : nullptr;
  }
  hyperhdrnet::Register *mutable_command_as_Register() {
    return command_type() == hyperhdrnet::Command_Register ? static_cast<hyperhdrnet::Register *>(mutable_command()) : nullptr;
  }
  void *mutable_command() {
    return GetPointer<void *>(VT_COMMAND);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_COMMAND_TYPE, 1) &&
           VerifyOffsetRequired(verifier, VT_COMMAND) &&
           VerifyCommand(verifier, command(), command_type()) &&
           verifier.EndTable();
  }
  RequestT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(RequestT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Request> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

template<> inline const hyperhdrnet::Color *Request::command_as<hyperhdrnet::Color>() const {
  return command_as_Color();
}

template<> inline hyperhdrnet::Color *Request::mutable_command_as<hyperhdrnet::Color>() {
  return mutable_command_as_Color();
}

template<> inline const hyperhdrnet::Image *Request::command_as<hyperhdrnet::Image>() const {
  return command_as_Image();
}

template<> inline hyperhdrnet::Image *Request::mutable_command_as<hyperhdrnet::Image>() {
  return mutable_command_as_Image();
}

template<> inline const hyperhdrnet::Clear *Request::command_as<hyperhdrnet::Clear>() const {
  return command_as_Clear();
}

template<> inline hyperhdrnet::Clear *Request::mutable_command_as<hyperhdrnet::Clear>() {
  return mutable_command_as_Clear();
}

template<> inline const hyperhdrnet::Register *Request::command_as<hyperhdrnet::Register>() const {
  return command_as_Register();
}

template<> inline hyperhdrnet::Register *Request::mutable_command_as<hyperhdrnet::Register>() {
  return mutable_command_as_Register();
}

struct RequestBuilder {
  typedef Request Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_command_type(hyperhdrnet::Command command_type) {
    fbb_.AddElement<uint8_t>(Request::VT_COMMAND_TYPE, static_cast<uint8_t>(command_type), 0);
  }
  void add_command(::flatbuffers::Offset<void> command) {
    fbb_.AddOffset(Request::VT_COMMAND, command);
  }
  explicit RequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Request> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Request>(end);
    fbb_.Required(o, Request::VT_COMMAND);
    return o;
  }
};

inline ::flatbuffers::Offset<Request> CreateRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    hyperhdrnet::Command command_type = hyperhdrnet::Command_NONE,
    ::flatbuffers::Offset<void> command = 0) {
  RequestBuilder builder_(_fbb);
  builder_.add_command(command);
  builder_.add_command_type(command_type);
  return builder_.Finish();
}

::flatbuffers::Offset<Request> CreateRequest(::flatbuffers::FlatBufferBuilder &_fbb, const RequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline RegisterT *Register::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<RegisterT>(new RegisterT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Register::UnPackTo(RegisterT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = origin(); if (_e) _o->origin = _e->str(); }
  { auto _e = priority(); _o->priority = _e; }
}

inline ::flatbuffers::Offset<Register> CreateRegister(::flatbuffers::FlatBufferBuilder &_fbb, const RegisterT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Register::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Register> Register::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RegisterT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const RegisterT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _origin = _fbb.CreateString(_o->origin);
  auto _priority = _o->priority;
  return hyperhdrnet::CreateRegister(
      _fbb,
      _origin,
      _priority);
}

inline RawImageT *RawImage::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<RawImageT>(new RawImageT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void RawImage::UnPackTo(RawImageT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = data(); if (_e) { _o->data.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->data.begin()); } }
  { auto _e = width(); _o->width = _e; }
  { auto _e = height(); _o->height = _e; }
}

inline ::flatbuffers::Offset<RawImage> CreateRawImage(::flatbuffers::FlatBufferBuilder &_fbb, const RawImageT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return RawImage::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<RawImage> RawImage::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RawImageT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const RawImageT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _data = _o->data.size() ? _fbb.CreateVector(_o->data) : 0;
  auto _width = _o->width;
  auto _height = _o->height;
  return hyperhdrnet::CreateRawImage(
      _fbb,
      _data,
      _width,
      _height);
}

inline NV12ImageT *NV12Image::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<NV12ImageT>(new NV12ImageT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void NV12Image::UnPackTo(NV12ImageT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = data_y(); if (_e) { _o->data_y.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->data_y.begin()); } }
  { auto _e = data_uv(); if (_e) { _o->data_uv.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->data_uv.begin()); } }
  { auto _e = width(); _o->width = _e; }
  { auto _e = height(); _o->height = _e; }
  { auto _e = stride_y(); _o->stride_y = _e; }
  { auto _e = stride_uv(); _o->stride_uv = _e; }
}

inline ::flatbuffers::Offset<NV12Image> CreateNV12Image(::flatbuffers::FlatBufferBuilder &_fbb, const NV12ImageT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return NV12Image::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<NV12Image> NV12Image::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const NV12ImageT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const NV12ImageT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _data_y = _o->data_y.size() ? _fbb.CreateVector(_o->data_y) : 0;
  auto _data_uv = _o->data_uv.size() ? _fbb.CreateVector(_o->data_uv) : 0;
  auto _width = _o->width;
  auto _height = _o->height;
  auto _stride_y = _o->stride_y;
  auto _stride_uv = _o->stride_uv;
  return hyperhdrnet::CreateNV12Image(
      _fbb,
      _data_y,
      _data_uv,
      _width,
      _height,
      _stride_y,
      _stride_uv);
}

inline ImageT *Image::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ImageT>(new ImageT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Image::UnPackTo(ImageT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = data_type(); _o->data.type = _e; }
  { auto _e = data(); if (_e) _o->data.value = hyperhdrnet::ImageTypeUnion::UnPack(_e, data_type(), _resolver); }
  { auto _e = duration(); _o->duration = _e; }
}

inline ::flatbuffers::Offset<Image> CreateImage(::flatbuffers::FlatBufferBuilder &_fbb, const ImageT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Image::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Image> Image::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ImageT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ImageT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _data_type = _o->data.type;
  auto _data = _o->data.Pack(_fbb);
  auto _duration = _o->duration;
  return hyperhdrnet::CreateImage(
      _fbb,
      _data_type,
      _data,
      _duration);
}

inline ClearT *Clear::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ClearT>(new ClearT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Clear::UnPackTo(ClearT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = priority(); _o->priority = _e; }
}

inline ::flatbuffers::Offset<Clear> CreateClear(::flatbuffers::FlatBufferBuilder &_fbb, const ClearT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Clear::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Clear> Clear::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ClearT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ClearT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _priority = _o->priority;
  return hyperhdrnet::CreateClear(
      _fbb,
      _priority);
}

inline ColorT *Color::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ColorT>(new ColorT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Color::UnPackTo(ColorT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = data(); _o->data = _e; }
  { auto _e = duration(); _o->duration = _e; }
}

inline ::flatbuffers::Offset<Color> CreateColor(::flatbuffers::FlatBufferBuilder &_fbb, const ColorT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Color::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Color> Color::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ColorT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ColorT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _data = _o->data;
  auto _duration = _o->duration;
  return hyperhdrnet::CreateColor(
      _fbb,
      _data,
      _duration);
}

inline RequestT *Request::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<RequestT>(new RequestT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Request::UnPackTo(RequestT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = command_type(); _o->command.type = _e; }
  { auto _e = command(); if (_e) _o->command.value = hyperhdrnet::CommandUnion::UnPack(_e, command_type(), _resolver); }
}

inline ::flatbuffers::Offset<Request> CreateRequest(::flatbuffers::FlatBufferBuilder &_fbb, const RequestT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Request::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Request> Request::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RequestT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const RequestT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _command_type = _o->command.type;
  auto _command = _o->command.Pack(_fbb);
  return hyperhdrnet::CreateRequest(
      _fbb,
      _command_type,
      _command);
}

template <bool B>
inline bool VerifyImageType(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, ImageType type) {
  switch (type) {
    case ImageType_NONE: {
      return true;
    }
    case ImageType_RawImage: {
      auto ptr = reinterpret_cast<const hyperhdrnet::RawImage *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ImageType_NV12Image: {
      auto ptr = reinterpret_cast<const hyperhdrnet::NV12Image *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyImageTypeVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyImageType(
        verifier,  values->Get(i), types->GetEnum<ImageType>(i))) {
      return false;
    }
  }
  return true;
}

inline void *ImageTypeUnion::UnPack(const void *obj, ImageType type, const ::flatbuffers::resolver_function_t *resolver) {
  (void)resolver;
  switch (type) {
    case ImageType_RawImage: {
      auto ptr = reinterpret_cast<const hyperhdrnet::RawImage *>(obj);
      return ptr->UnPack(resolver);
    }
    case ImageType_NV12Image: {
      auto ptr = reinterpret_cast<const hyperhdrnet::NV12Image *>(obj);
      return ptr->UnPack(resolver);
    }
    default: return nullptr;
  }
}

inline ::flatbuffers::Offset<void> ImageTypeUnion::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher) const {
  (void)_rehasher;
  switch (type) {
    case ImageType_RawImage: {
      auto ptr = reinterpret_cast<const hyperhdrnet::RawImageT *>(value);
      return CreateRawImage(_fbb, ptr, _rehasher).Union();
    }
    case ImageType_NV12Image: {
      auto ptr = reinterpret_cast<const hyperhdrnet::NV12ImageT *>(value);
      return CreateNV12Image(_fbb, ptr, _rehasher).Union();
    }
    default: return 0;
  }
}

inline ImageTypeUnion::ImageTypeUnion(const ImageTypeUnion &u) : type(u.type), value(nullptr) {
  switch (type) {
    case ImageType_RawImage: {
      value = new hyperhdrnet::RawImageT(*reinterpret_cast<hyperhdrnet::RawImageT *>(u.value));
      break;
    }
    case ImageType_NV12Image: {
      value = new hyperhdrnet::NV12ImageT(*reinterpret_cast<hyperhdrnet::NV12ImageT *>(u.value));
      break;
    }
    default:
      break;
  }
}

inline void ImageTypeUnion::Reset() {
  switch (type) {
    case ImageType_RawImage: {
      auto ptr = reinterpret_cast<hyperhdrnet::RawImageT *>(value);
      delete ptr;
      break;
    }
    case ImageType_NV12Image: {
      auto ptr = reinterpret_cast<hyperhdrnet::NV12ImageT *>(value);
      delete ptr;
      break;
    }
    default: break;
  }
  value = nullptr;
  type = ImageType_NONE;
}

template <bool B>
inline bool VerifyCommand(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, Command type) {
  switch (type) {
    case Command_NONE: {
      return true;
    }
    case Command_Color: {
      auto ptr = reinterpret_cast<const hyperhdrnet::Color *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Command_Image: {
      auto ptr = reinterpret_cast<const hyperhdrnet::Image *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Command_Clear: {
      auto ptr = reinterpret_cast<const hyperhdrnet::Clear *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Command_Register: {
      auto ptr = reinterpret_cast<const hyperhdrnet::Register *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyCommandVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyCommand(
        verifier,  values->Get(i), types->GetEnum<Command>(i))) {
      return false;
    }
  }
  return true;
}

inline void *CommandUnion::UnPack(const void *obj, Command type, const ::flatbuffers::resolver_function_t *resolver) {
  (void)resolver;
  switch (type) {
    case Command_Color: {
      auto ptr = reinterpret_cast<const hyperhdrnet::Color *>(obj);
      return ptr->UnPack(resolver);
    }
    case Command_Image: {
      auto ptr = reinterpret_cast<const hyperhdrnet::Image *>(obj);
      return ptr->UnPack(resolver);
    }
    case Command_Clear: {
      auto ptr = reinterpret_cast<const hyperhdrnet::Clear *>(obj);
      return ptr->UnPack(resolver);
    }
    case Command_Register: {
      auto ptr = reinterpret_cast<const hyperhdrnet::Register *>(obj);
      return ptr->UnPack(resolver);
    }
    default: return nullptr;
  }
}

inline ::flatbuffers::Offset<void> CommandUnion::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher) const {
  (void)_rehasher;
  switch (type) {
    case Command_Color: {
      auto ptr = reinterpret_cast<const hyperhdrnet::ColorT *>(value);
      return CreateColor(_fbb, ptr, _rehasher).Union();
    }
    case Command_Image: {
      auto ptr = reinterpret_cast<const hyperhdrnet::ImageT *>(value);
      return CreateImage(_fbb, ptr, _rehasher).Union();
    }
    case Command_Clear: {
      auto ptr = reinterpret_cast<const hyperhdrnet::ClearT *>(value);
      return CreateClear(_fbb, ptr, _rehasher).Union();
    }
    case Command_Register: {
      auto ptr = reinterpret_cast<const hyperhdrnet::RegisterT *>(value);
      return CreateRegister(_fbb, ptr, _rehasher).Union();
    }
    default: return 0;
  }
}

inline CommandUnion::CommandUnion(const CommandUnion &u) : type(u.type), value(nullptr) {
  switch (type) {
    case Command_Color: {
      value = new hyperhdrnet::ColorT(*reinterpret_cast<hyperhdrnet::ColorT *>(u.value));
      break;
    }
    case Command_Image: {
      value = new hyperhdrnet::ImageT(*reinterpret_cast<hyperhdrnet::ImageT *>(u.value));
      break;
    }
    case Command_Clear: {
      value = new hyperhdrnet::ClearT(*reinterpret_cast<hyperhdrnet::ClearT *>(u.value));
      break;
    }
    case Command_Register: {
      value = new hyperhdrnet::RegisterT(*reinterpret_cast<hyperhdrnet::RegisterT *>(u.value));
      break;
    }
    default:
      break;
  }
}

inline void CommandUnion::Reset() {
  switch (type) {
    case Command_Color: {
      auto ptr = reinterpret_cast<hyperhdrnet::ColorT *>(value);
      delete ptr;
      break;
    }
    case Command_Image: {
      auto ptr = reinterpret_cast<hyperhdrnet::ImageT *>(value);
      delete ptr;
      break;
    }
    case Command_Clear: {
      auto ptr = reinterpret_cast<hyperhdrnet::ClearT *>(value);
      delete ptr;
      break;
    }
    case Command_Register: {
      auto ptr = reinterpret_cast<hyperhdrnet::RegisterT *>(value);
      delete ptr;
      break;
    }
    default: break;
  }
  value = nullptr;
  type = Command_NONE;
}

inline const hyperhdrnet::Request *GetRequest(const void *buf) {
  return ::flatbuffers::GetRoot<hyperhdrnet::Request>(buf);
}

inline const hyperhdrnet::Request *GetSizePrefixedRequest(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<hyperhdrnet::Request>(buf);
}

inline Request *GetMutableRequest(void *buf) {
  return ::flatbuffers::GetMutableRoot<Request>(buf);
}

inline hyperhdrnet::Request *GetMutableSizePrefixedRequest(void *buf) {
  return ::flatbuffers::GetMutableSizePrefixedRoot<hyperhdrnet::Request>(buf);
}

template <bool B = false>
inline bool VerifyRequestBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<hyperhdrnet::Request>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedRequestBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<hyperhdrnet::Request>(nullptr);
}

inline void FinishRequestBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<hyperhdrnet::Request> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedRequestBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<hyperhdrnet::Request> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<hyperhdrnet::RequestT> UnPackRequest(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<hyperhdrnet::RequestT>(GetRequest(buf)->UnPack(res));
}

inline std::unique_ptr<hyperhdrnet::RequestT> UnPackSizePrefixedRequest(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<hyperhdrnet::RequestT>(GetSizePrefixedRequest(buf)->UnPack(res));
}

}  // namespace hyperhdrnet

#endif  // FLATBUFFERS_GENERATED_HYPERHDRREQUEST_HYPERHDRNET_H_
